steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #! /usr/bin/env bash
      set -eux
      docker build -t the-tag --target builder webapp
      docker create -it --name the-container the-tag
      mkdir /build
      docker cp the-container:/build/dist /build/dist
      ls -al /build/dist

artifacts:
  objects:
    location: 'gs://rlmcgraw-webapp-files'
    paths: ['/build/dist']

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
