steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #! /usr/bin/env bash -eux
      docker build -t webapp-image --target production webapp
      docker create -it --name my-container webapp-img
      mkdir /build
      docker cp my-container:/build/dist /build/dist
      ls -al /build/dist

artifacts:
  objects:
    location: 'gs://rlmcgraw-webapp-files'
    paths: ['/build/dist']

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
