steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #! /usr/bin/env bash
      set -eux
      docker build -t the-tag --target builder webapp
      docker create -it --name the-container the-tag
      docker cp the-container:/build/dist dist
      ls -al dist

      # Upload everything except index.html
      gsutil -m cp -r dist/* gs://rlmcgraw-webapp-files/ -x ".*index\.html$"
      
      # Upload index.html last
      gsutil cp dist/index.html gs://rlmcgraw-webapp-files/
      
      # Clean up old files
      gsutil -m rsync -r -d dist/ gs://rlmcgraw-webapp-files/

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
