steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #! /usr/bin/env bash
      set -eux
      docker build -t the-tag --target builder webapp
      docker create -it --name the-container the-tag
      docker cp the-container:/build/dist dist
      ls -al dist

artifacts:
  objects:
    location: 'gs://rlmcgraw-webapp-files/latest'
    paths: ['dist']

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
