steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #! /usr/bin/env bash
      set -eux
      docker build -t the-tag --target builder webapp
      docker create -it --name the-container the-tag
      docker cp the-container:/build/dist dist
      ls -al dist

  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      #! /usr/bin/env bash
      set -eux
      # Upload everything except index.html

      assets=$(find dist -type f | grep -v '^./dist/index.html$')
      echo "copying: ${assets}"
      gsutil -m cp -r "${assets}" gs://rlmcgraw-webapp-files/

      # Upload index.html last
      gsutil cp dist/index.html gs://rlmcgraw-webapp-files/
      
      # Clean up old files
      gsutil -m rsync -r -d dist/ gs://rlmcgraw-webapp-files/

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
