steps:
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      #! /usr/bin/env bash
      set -eux
      docker build -t the-tag --target builder webapp
      docker create -it --name the-container the-tag
      docker cp the-container:/build/dist dist
      ls -al dist

  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      #! /usr/bin/env bash
      set -eux
      # Upload everything except index.html

      indices=$(find dist -type f -name 'index.html' | tr '\n' ' ')
      assets=$(find dist -type f -not -name 'index.html' | tr '\n' ' ')

      gsutil ls gs://rlmcgraw-webapp-files/

      gsutil -m cp -r ${assets} gs://rlmcgraw-webapp-files/


      # Upload index.html last
      gsutil -m cp -r ${indices} gs://rlmcgraw-webapp-files/

      gsutil ls gs://rlmcgraw-webapp-files/

      # then we are going to invalidate the cach
      gcloud compute url-maps invalidate-cdn-cache webapp-lb \
        --path="/" \
        --path="/index.html" \
        --global
      
      # Clean up old files
      gsutil -m rsync -r -d dist/ gs://rlmcgraw-webapp-files/
      gsutil ls gs://rlmcgraw-webapp-files/

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
