services:
  
  webapp:
    build: ./webapp
    ports:
      - 8080:8080
    volumes:
      - ./webapp/src:/workdir/src
    environment:
      WATCHPACK_POLLING: true

  database:
    build: ./database
    volumes:
      # include sql file mounting to allow us to change flexibly
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: "rlmcgraw-webservice-user"
      MARIADB_PASSWORD: "password"
      MARIADB_DATABASE: "rlmcgraw"

